// BrightPath mock student pool — 20 profiles.
// Public tier fields (~80%, shown always) vs locked tier (~20%, unlocked post-sponsorship + guardian consent).
// Names are masked (first name + initial) per BrightPath's public-pool disclosure tier. No photos — avatar
// blocks use initials + colour only, never AI-generated or real imagery, at this tier.

const GRADIENTS = [
  ['#F4DCC5', '#1F5C4E'],
  ['#E7D3EF', '#153F35'],
  ['#F0DCC0', '#E2704A'],
  ['#FBEACD', '#8B5FA8'],
  ['#DCEAE3', '#B8532F']
];

const STUDENTS = [
  { id:1, name:'Ain A.', age:19, state:'Selangor', institution:'Diploma', course:'Nursing', academic:"5 A's in SPM", family:'Eldest of four, mother works as a school cafeteria cook.', story:"I want to be the first nurse in my kampung — someone people trust when they're scared.", goal:3000, raised:1850, interested:6, interviewDone:true, fund:{fees:1200,food:1300,travel:500} },
  { id:2, name:'Danial H.', age:18, state:'Sabah', institution:'Foundation', course:'Engineering', academic:"PNGK 3.6 (Matrikulasi)", family:'Father is a fisherman; family relies on seasonal catch income.', story:'My dream is to build bridges back to my hometown, literally and for the next kid like me.', goal:3000, raised:1020, interested:4, interviewDone:true, fund:{fees:1000,food:1200,travel:800} },
  { id:3, name:'Siti N.', age:19, state:'Kelantan', institution:'Diploma', course:'Accountancy', academic:"6 A's in SPM", family:'Single-parent household; mother sews for a living.', story:'I want to help my family manage money the right way, and then help others do the same.', goal:3000, raised:2430, interested:9, interviewDone:true, fund:{fees:1300,food:1200,travel:500} },
  { id:4, name:'Mei L.', age:19, state:'Pulau Pinang', institution:'Diploma', course:'Computer Science', academic:"PNGK 3.75 (Politeknik intake)", family:'Father is a hawker stall assistant; three younger siblings at home.', story:'I taught myself to code on a shared phone. Imagine what I can do with an actual laptop.', goal:3000, raised:640, interested:3, interviewDone:false, fund:{fees:1400,food:1100,travel:500} },
  { id:5, name:'Farah I.', age:20, state:'Kedah', institution:'Degree', course:'Education (TESL)', academic:"7 A's in SPM", family:'Rice-farming family; harvest income is unpredictable year to year.', story:'My own teachers changed my life. I want to be that for a village school someday.', goal:3000, raised:2980, interested:14, interviewDone:true, fund:{fees:1500,food:1100,travel:400} },
  { id:6, name:'Haziq R.', age:18, state:'Perak', institution:'Certificate', course:'Electrical Wiring (TVET)', academic:"4 A's, 3 B's in SPM", family:'Raised by grandparents; parents work out of state.', story:'I fix everything at home already. I just want the paper that says I can do it professionally.', goal:3000, raised:410, interested:2, interviewDone:false, fund:{fees:900,food:1300,travel:800} },
  { id:7, name:'Nurul A.', age:19, state:'Johor', institution:'Diploma', course:'Early Childhood Education', academic:"PNGK 3.5 (Politeknik intake)", family:'Mother is a part-time cleaner; father passed away in 2022.', story:'Every child deserves someone who notices when they are struggling. I want to be that person.', goal:3000, raised:1770, interested:5, interviewDone:true, fund:{fees:1100,food:1300,travel:600} },
  { id:8, name:'Amirul F.', age:19, state:'Sarawak', institution:'Foundation', course:'Pharmacy', academic:"PNGK 3.8 (Matrikulasi)", family:'Longhouse community; nearest hospital is two hours away.', story:'There is no pharmacist in my district. I want to be the reason someone gets their medicine on time.', goal:3000, raised:2210, interested:8, interviewDone:true, fund:{fees:1300,food:1000,travel:700} },
  { id:9, name:'Ling W.', age:18, state:'Melaka', institution:'Diploma', course:'Graphic Design', academic:"5 A's in SPM", family:'Family runs a small stall; income barely covers rent.', story:'I design posters for my mum’s stall for free. I want to learn to do this properly, for others too.', goal:3000, raised:980, interested:3, interviewDone:true, fund:{fees:1200,food:1300,travel:500} },
  { id:10, name:'Devi K.', age:20, state:'Negeri Sembilan', institution:'Degree', course:'Social Work', academic:"PNGK 3.65 (STPM)", family:'Youngest of five; two older siblings already working to support the family.', story:'Someone helped my family once. I want to be that someone for other families now.', goal:3000, raised:1560, interested:5, interviewDone:true, fund:{fees:1450,food:1150,travel:400} },
  { id:11, name:'Iman Z.', age:19, state:'Terengganu', institution:'Diploma', course:'Marine Science', academic:"6 A's in SPM", family:'Father is a boat mechanic; family income tied to fishing season.', story:'I grew up on the water. I want to help protect it for the next generation of fishermen.', goal:3000, raised:730, interested:4, interviewDone:false, fund:{fees:1200,food:1200,travel:600} },
  { id:12, name:'Zul H.', age:18, state:'Pahang', institution:'Certificate', course:'Automotive Technology', academic:"3 A's, 4 B's in SPM", family:'Father works at a palm oil estate; mother unwell, unable to work.', story:'I already help fix the neighbours’ motorcycles for free. I want a real workshop of my own one day.', goal:3000, raised:300, interested:2, interviewDone:false, fund:{fees:900,food:1400,travel:700} },
  { id:13, name:'Aisyah M.', age:19, state:'Selangor', institution:'Diploma', course:'Physiotherapy', academic:"PNGK 3.7 (Politeknik intake)", family:'Mother is a single parent working two cleaning jobs.', story:'My grandmother’s stroke recovery was slow because we couldn’t afford therapy. I want to change that for others.', goal:3000, raised:2050, interested:7, interviewDone:true, fund:{fees:1300,food:1200,travel:500} },
  { id:14, name:'Faris T.', age:19, state:'Kuala Lumpur', institution:'Foundation', course:'Architecture', academic:"PNGK 3.55 (Matrikulasi)", family:'Grew up in low-cost flats; father is a security guard.', story:'I want to design better low-cost housing — the kind that still feels like a home.', goal:3000, raised:1180, interested:4, interviewDone:true, fund:{fees:1350,food:1150,travel:500} },
  { id:15, name:'Wong K.', age:18, state:'Perlis', institution:'Diploma', course:'Agriculture Technology', academic:"5 A's in SPM", family:'Family owns a small padi plot; yields have dropped in recent years.', story:'I want to bring better farming methods home so my family’s land can feed more than just us.', goal:3000, raised:540, interested:2, interviewDone:false, fund:{fees:1100,food:1200,travel:700} },
  { id:16, name:'Adam S.', age:20, state:'Sabah', institution:'Degree', course:'Business Management', academic:"PNGK 3.5 (STPM)", family:'Orphaned at 14; raised by an aunt with four other children.', story:'I want to start a business that hires people like me — people who almost didn’t get a chance.', goal:3000, raised:2670, interested:11, interviewDone:true, fund:{fees:1450,food:1050,travel:500} },
  { id:17, name:'Nabil Q.', age:19, state:'Kelantan', institution:'Certificate', course:'Culinary Arts', academic:"4 A's, 5 B's in SPM", family:'Mother sells kuih at the pasar pagi; sole income for the household.', story:'I already help my mother cook before school. I want to turn that into a real career.', goal:3000, raised:890, interested:3, interviewDone:true, fund:{fees:1000,food:1400,travel:600} },
  { id:18, name:'Balqis Y.', age:19, state:'Labuan', institution:'Diploma', course:'Mass Communication', academic:"6 A's in SPM", family:'Father works offshore; long stretches without him at home.', story:'I want to tell the stories of island communities that usually get left out of the news.', goal:3000, raised:1340, interested:5, interviewDone:false, fund:{fees:1200,food:1000,travel:800} },
  { id:19, name:'Hakim J.', age:18, state:'Johor', institution:'Foundation', course:'Medical Laboratory Technology', academic:"PNGK 3.65 (Matrikulasi)", family:'Both parents work in a factory on rotating shifts.', story:'I want to be the person behind the scenes who catches what a diagnosis might miss.', goal:3000, raised:1970, interested:6, interviewDone:true, fund:{fees:1300,food:1200,travel:500} },
  { id:20, name:'Suriani P.', age:20, state:'Sarawak', institution:'Degree', course:'Law (Foundation year)', academic:"PNGK 3.8 (STPM)", family:'Grew up in a rural longhouse; first in her family to pursue tertiary education.', story:'I’ve seen how confusing the law can be for people who can’t afford a lawyer. I want to be the free version of that for my community.', goal:3000, raised:2890, interested:13, interviewDone:true, fund:{fees:1500,food:1000,travel:500} }
];

function fmtRM(n){ return 'RM' + Math.round(n).toLocaleString('en-MY'); }
function pctFunded(s){ return Math.min(100, Math.round((s.raised / s.goal) * 100)); }
function gradientFor(id){ return GRADIENTS[(id - 1) % GRADIENTS.length]; }
function getStudentById(id){ return STUDENTS.find(function(s){ return s.id === Number(id); }); }
